name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install forge
      run: cargo install --git https://github.com/gakonst/foundry --bin forge --locked
    - name: Install dependencies
      run: make
    - name: Run tests
      run: forge test
